default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  host: 127.0.0.1
  port: 3306
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>

development:
  <<: *default
  database: elasticsearch_dev

test:
  <<: *default
  database: elasticsearch_test
